AWSTemplateFormatVersion: "2010-09-09"
Resources:
  playerDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "symbol"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "symbol"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "mystock_share"
