AWSTemplateFormatVersion: "2010-09-09"
Resources:
  sharesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "symbol"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "symbol"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "mystock-shares"
  currenciesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "currency"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "currency"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "mystock-currencies"
