module.exports = Object.freeze({
  SYMBOL: 'symbol',
  INDERES_INSTRUCTION: 'inderesInstruction',
  YIELD: 'yield',
  DIVIDEND_YIELD: 'dividendYield',
  POTENTIAL: 'potential',
  MARKET_PRICE_EUR: 'marketPriceEur',
  YIELD_EUR: 'yieldEur',
  EXPECTED_GROWTH_EUR: 'expectedGrowthEur',
  EXPECTED_MARKET_PRICE_EUR: 'expectedMarketPriceEur',
  EXPECTED_WIN_EUR: 'expectedWinEur',
  EXPECTED_GROWTH_FROM_START: 'expectedGrowthFromStart',
  AMOUNT_OF_STOCK: 'amountOfStocks',
  MIDDLE_RATE: 'middleRate',
  PURCHASE_PRICE: 'purchasePrice',
  PRICE: 'price',
  INDERES_TARGET_PRICE: 'inderesTargetPrice',
  RESULT_EQUITY: 'resultEquity',
  PRICE_TO_EARNINGS: 'priceToEarnings',
  PRICE_TO_SALES: 'priceToSales',
  PRICE_TO_BOOK: 'priceToBook',
  PRICE_TO_MARKET_LOCAL: 'marketPriceLocal',
  PURCHASE_PRICE_EUR: 'purchasePriceEur',
  PERCENTAGE_OF_PORTFOLIO: 'percentageOfPortfolio'
});
