service: mystock-shares

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  apiKeys:
    - mystock-apikey
  environment:
    DYNAMODB_TABLE_SHARES: mystock-shares
    DYNAMODB_TABLE_CURRENCIES: mystock-currencies
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_SHARES}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_CURRENCIES}"

functions:
  list_shares:
    handler: index.list_shares
    events:
      - http:
          path: shares
          method: get
          cors: true
          private: true
  get_share:
    handler: index.get_share
    events:
      - http:
          path: shares/{symbol}
          method: get
          cors: true
          private: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'mystock.cloud.tovrleaf.com'
    certificateName: '*.cloud.tovrleaf.com'
    basePath: 'api'
    stage: ${self:provider.stage}
    createRoute53Record: true
